# fly.toml file generated for msc-modmail on 2022-08-26T00:51:48+01:00

app = "msc-modmail"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  SWAP = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []
