# fly.toml app configuration file generated for msc-modmail on 2023-05-26T15:23:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "msc-modmail"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "rolling"

[env]
  SWAP = "true"
